### ISSUE TITLE
🚓(admin) 채팅 / 매장 운영상태 변경

### ISSUE THREAD

**Issue by younssue** [Nailborhood/backend#36]
## ✅ Feature
admin 매장 운영 상태 변경 
## Description
관리자와 사업자 채팅완료 후 
사업자가 매장 운영을 폐업 신고 하면 매장 운영 상태를 변경으로 처리 

## Todo

- [ ] 채팅 관련 공부 
- [ ] 채팅 기능 분류
- [ ] 매장 운영 상태 변경 

## ETC
- 주의 사항 혹은 기타 내용
